### ISSUE TITLE
Rates API endpoint, rates key with values bid/offer/both

### ISSUE THREAD

**Issue by HLFH** [CurrencyCloud/currencycloud-ruby#11]
Hi,

I would like the option to only ask for bid rates, only ask for offer rates, or both.

https://github.com/CurrencyCloud/currencycloud-ruby/blob/master/lib/currency_cloud/rate.rb

Here, without the offer rates, it becomes:
```ruby
module CurrencyCloud
  class Rate
    include CurrencyCloud::Resource

    resource :rates

    def self.find(params)
      response = client.get("find", params)

      rates = response["rates"].map do |currency_pair, (bid)|
        new(currency_pair: currency_pair, bid: bid)
      end

      Rates.new(currencies: rates, unavailable: response["unavailable"])
    end

    def self.detailed(params)
      new(client.get("detailed", params))
    end
  end
end
```

In fact, in my case, I only need bid rates. Do you plan to have a key on your [rates/find API endpoint](https://developer.currencycloud.com/documentation/api-docs/rates/get-rates-find/), called `rates` with type `string` and values `bid`, `offer` or `both`?

And btw, do you plan to implement GraphQL for the V3 of your API?

Thank you,

**Comment by EAddario** [comment]
We may introduce this in a future release
