### ISSUE TITLE
Using Multiple API Keys/Sessions/Authentication Tokens

### ISSUE THREAD

**Issue by artsyca** [CurrencyCloud/currencycloud-ruby#8]
In a multi-user environment, can this be done? To allow each user to have their own API Session?

Would it be enough to switch out `@session` and `@token?`

Are there any other concerns around this? I would be open to contributing the solution through a PR.

**Comment by rjnienaber** [comment]
> To allow each user to have their own API Session?

I think the intention is that the `on_behalf_of` parameter should cover this scenario. What specific use case are you trying to cover?

**Comment by artsyca** [comment]
We have multiple traders using our app, each with their own maximum trade
limits.

We need to ensure these limits are not exceeded and to that end
CurrencyCloud have assigned us an API token per user.

I'm open to suggestions on alternative strategies but it seems that
`on_behalf_of` would not work for imposing trade limits?

So we are trying to give each trader their own session.

**Comment by artsyca** [comment]
After further discussion with CC, it's now apparent that `on_behalf_of` does indeed effect the needed functionality! Closing this issue as it is no longer the optimal solution.
